export const dropdownOptions = [
    { value: "afghan", label: "Afghan" },
    { value: "albanian", label: "Albanian" },
    { value: "algerian", label: "Algerian" },
    { value: "american", label: "American" },
    { value: "andorran", label: "Andorran" },
    { value: "angolan", label: "Angolan" },
    { value: "antiguan", label: "Antiguan" },
    { value: "argentine", label: "Argentine" },
    { value: "armenian", label: "Armenian" },
    { value: "australian", label: "Australian" },
    { value: "austrian", label: "Austrian" },
    { value: "azerbaijani", label: "Azerbaijani" },
    { value: "bahamian", label: "Bahamian" },
    { value: "bahraini", label: "Bahraini" },
    { value: "bangladeshi", label: "Bangladeshi" },
    { value: "barbadian", label: "Barbadian" },
    { value: "belarusian", label: "Belarusian" },
    { value: "belgian", label: "Belgian" },
    { value: "belizean", label: "Belizean" },
    { value: "beninese", label: "Beninese" },
    { value: "bhutanese", label: "Bhutanese" },
    { value: "bolivian", label: "Bolivian" },
    { value: "bosnian", label: "Bosnian" },
    { value: "botswanan", label: "Botswanan" },
    { value: "brazilian", label: "Brazilian" },
    { value: "british", label: "British" },
    { value: "bruneian", label: "Bruneian" },
    { value: "bulgarian", label: "Bulgarian" },
    { value: "burkinabe", label: "Burkinabe" },
    { value: "burmese", label: "Burmese" },
    { value: "burundian", label: "Burundian" },
    { value: "cambodian", label: "Cambodian" },
    { value: "cameroonian", label: "Cameroonian" },
    { value: "canadian", label: "Canadian" },
    { value: "cape_verdean", label: "Cape Verdean" },
    { value: "central_african", label: "Central African" },
    { value: "chadian", label: "Chadian" },
    { value: "chilean", label: "Chilean" },
    { value: "chinese", label: "Chinese" },
    { value: "colombian", label: "Colombian" },
    { value: "comoran", label: "Comoran" },
    { value: "congolese", label: "Congolese" },
    { value: "costa_rican", label: "Costa Rican" },
    { value: "croatian", label: "Croatian" },
    { value: "cuban", label: "Cuban" },
    { value: "cypriot", label: "Cypriot" },
    { value: "czech", label: "Czech" },
    { value: "danish", label: "Danish" },
    { value: "djiboutian", label: "Djiboutian" },
    { value: "dominican", label: "Dominican" },
    { value: "dutch", label: "Dutch" },
    { value: "east_timorese", label: "East Timorese" },
    { value: "ecuadorean", label: "Ecuadorean" },
    { value: "egyptian", label: "Egyptian" },
    { value: "emirati", label: "Emirati" },
    { value: "equatorial_guinean", label: "Equatorial Guinean" },
    { value: "eritrean", label: "Eritrean" },
    { value: "estonian", label: "Estonian" },
    { value: "ethiopian", label: "Ethiopian" },
    { value: "fijian", label: "Fijian" },
    { value: "finnish", label: "Finnish" },
    { value: "french", label: "French" },
    { value: "gabonese", label: "Gabonese" },
    { value: "gambian", label: "Gambian" },
    { value: "georgian", label: "Georgian" },
    { value: "german", label: "German" },
    { value: "ghanaian", label: "Ghanaian" },
    { value: "greek", label: "Greek" },
    { value: "grenadian", label: "Grenadian" },
    { value: "guatemalan", label: "Guatemalan" },
    { value: "guinean", label: "Guinean" },
    { value: "guinea_bissauan", label: "Guinea-Bissauan" },
    { value: "guyanese", label: "Guyanese" },
    { value: "haitian", label: "Haitian" },
    { value: "honduran", label: "Honduran" },
    { value: "hungarian", label: "Hungarian" },
    { value: "icelander", label: "Icelander" },
    { value: "indian", label: "Indian" },
    { value: "indonesian", label: "Indonesian" },
    { value: "iranian", label: "Iranian" },
    { value: "iraqi", label: "Iraqi" },
    { value: "irish", label: "Irish" },
    { value: "italian", label: "Italian" },
    { value: "ivorian", label: "Ivorian" },
    { value: "jamaican", label: "Jamaican" },
    { value: "japanese", label: "Japanese" },
    { value: "jordanian", label: "Jordanian" },
    { value: "kazakh", label: "Kazakh" },
    { value: "kenyan", label: "Kenyan" },
    { value: "kittian_nevisian", label: "Kittian and Nevisian" },
    { value: "kuwaiti", label: "Kuwaiti" },
    { value: "kyrgyz", label: "Kyrgyz" },
    { value: "laotian", label: "Laotian" },
    { value: "latvian", label: "Latvian" },
    { value: "lebanese", label: "Lebanese" },
    { value: "liberian", label: "Liberian" },
    { value: "libyan", label: "Libyan" },
    { value: "liechtensteiner", label: "Liechtensteiner" },
    { value: "lithuanian", label: "Lithuanian" },
    { value: "luxembourger", label: "Luxembourger" },
    { value: "macedonian", label: "Macedonian" },
    { value: "malagasy", label: "Malagasy" },
    { value: "malawian", label: "Malawian" },
    { value: "malaysian", label: "Malaysian" },
    { value: "maldivian", label: "Maldivian" },
    { value: "malian", label: "Malian" },
    { value: "maltese", label: "Maltese" },
    { value: "marshallese", label: "Marshallese" },
    { value: "mauritanian", label: "Mauritanian" },
    { value: "mauritian", label: "Mauritian" },
    { value: "mexican", label: "Mexican" },
    { value: "micronesian", label: "Micronesian" },
    { value: "moldovan", label: "Moldovan" },
    { value: "monacan", label: "Monacan" },
    { value: "mongolian", label: "Mongolian" },
    { value: "montenegrin", label: "Montenegrin" },
    { value: "moroccan", label: "Moroccan" },
    { value: "mozambican", label: "Mozambican" },
    { value: "namibian", label: "Namibian" },
    { value: "nauruan", label: "Nauruan" },
    { value: "nepalese", label: "Nepalese" },
    { value: "new_zealander", label: "New Zealander" },
    { value: "nicaraguan", label: "Nicaraguan" },
    { value: "nigerien", label: "Nigerien" },
    { value: "nigerian", label: "Nigerian" },
    { value: "norwegian", label: "Norwegian" },
    { value: "omani", label: "Omani" },
    { value: "pakistani", label: "Pakistani" },
    { value: "palestinian", label: "Palestinian" },
    // Add more as necessary.
];

export const roomMaintenanceIssues = [
    { value: "room_maintenance_issues", label: "Room Maintenance Issues" },
    { value: "socket_equipment_stuck", label: "Socket some equipment stuck" },
    { value: "socket_sparks", label: "Socket some sparks" },
    { value: "socket_no_electricity", label: "Socket some no electricity" },
    { value: "socket_burned", label: "Socket some burned" },
    { value: "room_light_furniture_flickering", label: "Room light furniture area flickering" },
    { value: "room_light_furniture_not_working", label: "Room light furniture area not working at all" },
    { value: "room_light_beds_flickering", label: "Room light beds area flickering" },
    { value: "room_light_beds_not_working", label: "Room light beds area not working at all" },
    { value: "general_washroom_light_not_working", label: "General washroom light not working" },
    { value: "general_washroom_light_flickering", label: "General washroom light flickering" },
    { value: "toilet_light_not_working", label: "Toilet light not working at all" },
    { value: "toilet_light_flickering", label: "Toilet light flickering" },
    { value: "fan_beds_slow", label: "Fan beds area slow" },
    { value: "fan_beds_not_working", label: "Fan beds area not working at all" },
    { value: "fan_furniture_slow", label: "Fan furniture area slow" },
    { value: "fan_furniture_not_working", label: "Fan furniture area not working at all" },
    { value: "ventilation_issue", label: "Ventilation issue" },
    { value: "air_conditioner_leakage", label: "Air conditioner water leakage" },
    { value: "washroom_tap_shower_broken", label: "Washroom water tap shower broken" },
    { value: "sink_tap_loose", label: "Sink water tap loose" },
    { value: "toilet_tap_loose", label: "Toilet water tap is loose" },
    { value: "toilet_tap_damage", label: "Toilet water tap damage" },
    { value: "no_water_from_tap", label: "No water from water tap" },
    { value: "toilet_storage_leakage", label: "Toilet water storage leakage" },
    { value: "sink_clogged", label: "Sink clogged" },
    { value: "washroom_drain_clogged", label: "Washroom drain clogged" },
    { value: "toilet_flush_not_working", label: "Toilet flush not working" },
    { value: "water_dispenser_slow", label: "Water dispenser water slow" },
    { value: "sink_tap_broken", label: "Sink water tap broken" },
    { value: "sink_pipe_leakage", label: "Sink pipe leakage" },
    { value: "toilet_door_lock_broken", label: "Toilet door lock broken" },
    { value: "door_knob_stuck", label: "Door knob stuck/jammed" },
    { value: "toilet_door_damaged", label: "Toilet door damage/broken/hole" },
    { value: "washroom_door_lock_broken", label: "Washroom door lock broken" },
    { value: "washroom_door_damaged", label: "Washroom door damage/broken/hole" },
    { value: "wardrobe_key_jammed", label: "Wardrobe key lock jammed" },
    { value: "room_key_lost", label: "Room key lost" },
    { value: "all_keys_missing", label: "All room and wardrobe keys missing" },
    { value: "bed_frame_broken", label: "Bed frame broken" },
    { value: "wardrobe_keys_not_working", label: "Wardrobe keys both sides not working" },
    { value: "sofa_damaged", label: "Sofa damaged" },
    { value: "fridge_not_working", label: "Fridge 06 not working" },
    { value: "fridge_freezer_problem", label: "Fridge freezer problem" },
    { value: "fridge_chiller_problem", label: "Fridge chiller problem" },
    { value: "water_cooler_not_working", label: "Water cooler not working properly" },
    { value: "ceiling_leaking", label: "Ceiling is leaking" },
    { value: "roof_ceiling_leaking", label: "Roof/ceiling leaking" },
    { value: "wall_leaking", label: "Wall water leaking" },
    { value: "toilet_drain_no_cover", label: "Toilet drain hole no cover" },
    { value: "washroom_drain_no_cover", label: "Washroom drain hole no cover" },
    { value: "pest_infestation", label: "Pest infestation reported" },
    { value: "cockroach_issue", label: "Cockroach issue" },
    { value: "mosquito_issue", label: "Mosquito issue" },
    { value: "rat_infestation", label: "Rat infestation" }
];

export const religions = [
    { value: "christianity", label: "Christianity" },
    { value: "islam", label: "Islam" },
    { value: "secular", label: "Secular/Non-religious/Atheism" },
    { value: "hinduism", label: "Hinduism" },
    { value: "buddhism", label: "Buddhism" },
    { value: "traditional-folk-religions", label: "Traditional Folk Religions" },
    { value: "sikhism", label: "Sikhism" },
    { value: "judaism", label: "Judaism" },
    { value: "jainism", label: "Jainism" },
    { value: "bahai", label: "Bahá'í Faith" },
    { value: "shinto", label: "Shinto" },
    { value: "zoroastrianism", label: "Zoroastrianism" },
];
