export const nationalities = [
    [
        { value: "afghan", label: "Afghan" },
        { value: "albanian", label: "Albanian" },
        { value: "algerian", label: "Algerian" },
        { value: "american", label: "American" },
        { value: "andorran", label: "Andorran" },
        { value: "angolan", label: "Angolan" },
        { value: "antiguan_barbudan", label: "Antiguan/Barbudan" },
        { value: "argentine", label: "Argentine" },
        { value: "armenian", label: "Armenian" },
        { value: "australian", label: "Australian" },
        { value: "austrian", label: "Austrian" },
        { value: "azerbaijani", label: "Azerbaijani" },
        { value: "bahraini", label: "Bahraini" },
        { value: "comorian", label: "Comorian" },
        { value: "djiboutian", label: "Djiboutian" },
        { value: "egyptian", label: "Egyptian" },
        { value: "emirati", label: "Emirati" },
        { value: "iraqi", label: "Iraqi" },
        { value: "jordanian", label: "Jordanian" },
        { value: "kuwaiti", label: "Kuwaiti" },
        { value: "lebanese", label: "Lebanese" },
        { value: "libyan", label: "Libyan" },
        { value: "mauritanian", label: "Mauritanian" },
        { value: "moroccan", label: "Moroccan" },
        { value: "omani", label: "Omani" },
        { value: "palestinian", label: "Palestinian" },
        { value: "qatari", label: "Qatari" },
        { value: "saudi", label: "Saudi" },
        { value: "somali", label: "Somali" },
        { value: "sudanese", label: "Sudanese" },
        { value: "syrian", label: "Syrian" },
        { value: "tunisian", label: "Tunisian" },
        { value: "yemeni", label: "Yemeni" },
        { value: "other", label: "Other" }
    ]

];

export const roomMaintenanceIssues = [
    {value: "room_maintenance_issues", label: "Room Maintenance Issues"},
    {value: "socket_equipment_stuck", label: "Socket some equipment stuck"},
    {value: "socket_sparks", label: "Socket some sparks"},
    {value: "socket_no_electricity", label: "Socket some no electricity"},
    {value: "socket_burned", label: "Socket some burned"},
    {value: "room_light_furniture_flickering", label: "Room light furniture area flickering"},
    {value: "room_light_furniture_not_working", label: "Room light furniture area not working at all"},
    {value: "room_light_beds_flickering", label: "Room light beds area flickering"},
    {value: "room_light_beds_not_working", label: "Room light beds area not working at all"},
    {value: "general_washroom_light_not_working", label: "General washroom light not working"},
    {value: "general_washroom_light_flickering", label: "General washroom light flickering"},
    {value: "toilet_light_not_working", label: "Toilet light not working at all"},
    {value: "toilet_light_flickering", label: "Toilet light flickering"},
    {value: "fan_beds_slow", label: "Fan beds area slow"},
    {value: "fan_beds_not_working", label: "Fan beds area not working at all"},
    {value: "fan_furniture_slow", label: "Fan furniture area slow"},
    {value: "fan_furniture_not_working", label: "Fan furniture area not working at all"},
    {value: "ventilation_issue", label: "Ventilation issue"},
    {value: "air_conditioner_leakage", label: "Air conditioner water leakage"},
    {value: "washroom_tap_shower_broken", label: "Washroom water tap shower broken"},
    {value: "sink_tap_loose", label: "Sink water tap loose"},
    {value: "toilet_tap_loose", label: "Toilet water tap is loose"},
    {value: "toilet_tap_damage", label: "Toilet water tap damage"},
    {value: "no_water_from_tap", label: "No water from water tap"},
    {value: "toilet_storage_leakage", label: "Toilet water storage leakage"},
    {value: "sink_clogged", label: "Sink clogged"},
    {value: "washroom_drain_clogged", label: "Washroom drain clogged"},
    {value: "toilet_flush_not_working", label: "Toilet flush not working"},
    {value: "water_dispenser_slow", label: "Water dispenser water slow"},
    {value: "sink_tap_broken", label: "Sink water tap broken"},
    {value: "sink_pipe_leakage", label: "Sink pipe leakage"},
    {value: "toilet_door_lock_broken", label: "Toilet door lock broken"},
    {value: "door_knob_stuck", label: "Door knob stuck/jammed"},
    {value: "toilet_door_damaged", label: "Toilet door damage/broken/hole"},
    {value: "washroom_door_lock_broken", label: "Washroom door lock broken"},
    {value: "washroom_door_damaged", label: "Washroom door damage/broken/hole"},
    {value: "wardrobe_key_jammed", label: "Wardrobe key lock jammed"},
    {value: "room_key_lost", label: "Room key lost"},
    {value: "all_keys_missing", label: "All room and wardrobe keys missing"},
    {value: "bed_frame_broken", label: "Bed frame broken"},
    {value: "wardrobe_keys_not_working", label: "Wardrobe keys both sides not working"},
    {value: "sofa_damaged", label: "Sofa damaged"},
    {value: "fridge_not_working", label: "Fridge 06 not working"},
    {value: "fridge_freezer_problem", label: "Fridge freezer problem"},
    {value: "fridge_chiller_problem", label: "Fridge chiller problem"},
    {value: "water_cooler_not_working", label: "Water cooler not working properly"},
    {value: "ceiling_leaking", label: "Ceiling is leaking"},
    {value: "roof_ceiling_leaking", label: "Roof/ceiling leaking"},
    {value: "wall_leaking", label: "Wall water leaking"},
    {value: "toilet_drain_no_cover", label: "Toilet drain hole no cover"},
    {value: "washroom_drain_no_cover", label: "Washroom drain hole no cover"},
    {value: "pest_infestation", label: "Pest infestation reported"},
    {value: "cockroach_issue", label: "Cockroach issue"},
    {value: "mosquito_issue", label: "Mosquito issue"},
    {value: "rat_infestation", label: "Rat infestation"}
];

export const religions = [
    {value: "christianity", label: "Christianity"},
    {value: "islam", label: "Islam"},
    {value: "secular", label: "Secular/Non-religious/Atheism"},
    {value: "hinduism", label: "Hinduism"},
    {value: "buddhism", label: "Buddhism"},
    {value: "traditional-folk-religions", label: "Traditional Folk Religions"},
    {value: "sikhism", label: "Sikhism"},
    {value: "judaism", label: "Judaism"},
    {value: "jainism", label: "Jainism"},
    {value: "bahai", label: "Bahá'í Faith"},
    {value: "shinto", label: "Shinto"},
    {value: "zoroastrianism", label: "Zoroastrianism"},
];
